# github-action/hub-workflow.yml

name: Terraform Hub

on:
  push:
    branches:
      - main
    paths:
      - 'hub/**'
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=tdtfstate" \
          -backend-config="storage_account_name=tdtfstatestorage" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=hub.tfstate"
      working-directory: ./hub

    - name: Terraform Plan
      run: terraform plan -var-file=environments/dev.tfvars -out=tfplan
      working-directory: ./hub

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: hub/tfplan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=tdtfstate" \
          -backend-config="storage_account_name=tdtfstatestorage" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=hub.tfstate"
      working-directory: ./hub

    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: tfplan
        path: hub

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./hub