# github-action/spoke-workflow.yml

name: Terraform Spoke

on:
  push:
    branches:
      - main
    paths:
      - 'spok/**'
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: "9734ed68-621d-47ed-babd-269110dbacb1"
      ARM_TENANT_ID: "84f1e4ea-8554-43e1-8709-f0b8589ea118"
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=tdtfstate" \
          -backend-config="storage_account_name=tdtfstatestorage" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=spoke.tfstate"
      working-directory: ./spok1

    - name: Terraform Plan
      run: terraform plan -var-file=spoke.tfvars -out=tfplan
      working-directory: ./spok1

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: spok/tfplan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2

    - name: Azure CLI Login
      run: |
        az login --use-device-code
        az account set --subscription "9734ed68-621d-47ed-babd-269110dbacb1"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=1-7a15c9ff-playground-sandbox" \
          -backend-config="storage_account_name=tdtfstate" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=spoke.tfstate"
      working-directory: ./spok1

    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: tfplan
        path: spok

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./spok1