# github-action/hub-workflow.yml

name: Terraform Hub

on:
  push:
    branches:
      - main
    paths:
      - 'hub/**'
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: "28e1e42a-4438-4c30-9a5f-7d7b488fd883"
      ARM_TENANT_ID: "84f1e4ea-8554-43e1-8709-f0b8589ea118"
    
    steps:
    - uses: actions/checkout@v2

    - name: Azure CLI Login
      run: |
        az login --use-device-code
        az account set --subscription "28e1e42a-4438-4c30-9a5f-7d7b488fd883"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.5.7

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=1-7a15c9ff-playground-sandbox" \
          -backend-config="storage_account_name=tdtfstate" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=hub.tfstate"
      working-directory: ./hub

    - name: Terraform Plan
      run: terraform plan -var-file=hub.tfvars -out=tfplan
      working-directory: ./hub

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: hub/tfplan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.5.7
      

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=tdtfstate" \
          -backend-config="storage_account_name=tdtfstatestorage" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=hub.tfstate"
      working-directory: ./hub

    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: tfplan
        path: hub

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./hub